require:
  - rubocop-rails
  - rubocop-rake
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.6
  NewCops: enable
  Exclude:
    - bin/rails
    - db/schema.rb
    - vendor/**/*

RSpec:
  Language:
    ExampleGroups:
      Regular:
        - wrap_context
      Skipped:
        - xwrap_context
      Focused:
        - fwrap_context
    Includes:
      Examples:
        - include_contract
        - finclude_contract
        - fwrap_examples
        - wrap_examples
        - xinclude_contract
        - xwrap_examples

Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/HashAlignment:
  EnforcedColonStyle:      table
  EnforcedHashRocketStyle: table

Layout/LineLength:
  Max: 80

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Metrics/BlockLength:
  Exclude:
    - '*.gemspec'
    - lib/**/*_contract.rb
    - spec/support/**/*_examples.rb
    - spec/spec_helper.rb
    - spec/**/*_spec.rb

Metrics/ModuleLength:
  Exclude:
    - lib/**/*_contract.rb
    - spec/**/*_examples.rb

Naming/RescuedExceptionsVariableName:
  PreferredName: exception

RSpec/ExampleWording:
  Enabled: false

RSpec/HookArgument:
  Enabled: false

RSpec/LeadingSubject:
  Enabled: false # Prefer shared examples at top of file.

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/NestedGroups:
  Max: 5

Style/AccessorGrouping:
  EnforcedStyle: separated

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Exclude:
    - config/**/*.rb
    - db/migrate/*
    - spec/support/**/*.rb

RSpec/FilePath:
  Exclude:
    - spec/integration/**/*

Style/NestedParenthesizedCalls:
  Exclude:
    - 'spec/**/*'

Style/TrailingUnderscoreVariable:
  Enabled: false
