plugins:
  - rubocop-factory_bot
  - rubocop-rails
  - rubocop-rake
  - rubocop-rspec
  - rubocop-rspec_rails

inherit_gem:
  rspec-sleeping_king_studios: config/rubocop-rspec.yml

AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable
  Exclude:
    - bin/rails
    - db/schema.rb
    - gemfiles/*
    - vendor/**/*

Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/HashAlignment:
  EnforcedColonStyle:      table
  EnforcedHashRocketStyle: table

Layout/LineLength:
  AllowedPatterns:
    - '\A\s*#'
  Max: 80

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Metrics/BlockLength:
  Exclude:
    - '*.gemspec'
    - lib/**/*_contract.rb
    - lib/**/*_contracts.rb
    - lib/**/*_examples.rb
    - spec/spec_helper.rb
    - spec/**/*_examples.rb
    - spec/**/*_spec.rb

Metrics/ModuleLength:
  Exclude:
    - lib/**/*_contract.rb
    - lib/**/*_contracts.rb
    - lib/**/*_examples.rb
    - spec/**/*_examples.rb

Naming/RescuedExceptionsVariableName:
  PreferredName: exception

Rails/IndexWith:
  Enabled: false

RSpec/BeNil:
  Enabled: false

RSpec/Eq:
  Enabled: false

RSpec/ExampleWording:
  Enabled: false

RSpec/HookArgument:
  Enabled: false

RSpec/LeadingSubject:
  Enabled: false # Prefer shared examples at top of file.

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/NestedGroups:
  Max: 5

RSpec/SpecFilePathFormat:
  Exclude:
    - spec/integration/**/*

RSpecRails/HaveHttpStatus:
  Enabled: false

Style/AccessorGrouping:
  EnforcedStyle: separated

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Exclude:
    - config/**/*.rb
    - db/migrate/*
    - spec/support/**/*.rb

Style/NestedParenthesizedCalls:
  Exclude:
    - 'spec/**/*'

Style/RedundantLineContinuation:
  Exclude:
    - 'spec/**/*'

Style/TrailingUnderscoreVariable:
  Enabled: false
