# Build Options
language: ruby
rvm:
  - 2.6.7
  - 2.7.3
before_script:
  - cp .rspec.example .rspec
  - cp .rubocop.example .rubocop
script:
  - bundle exec thor ci:steps

# Travis-CI Configuration
cache: bundler
sudo:  false # Enable containerized builds.
