# Build Options
language: ruby
env:
  global:
    - PGPORT=5433
rvm:
  - 2.6.8
  - 2.7.4
  - 3.0.2
before_script:
  - cp .rspec.example .rspec
  - cp .rubocop.example .rubocop
script:
  - bundle exec rake db:test:prepare
  - bundle exec thor ci:steps

# Travis-CI Configuration
cache: bundler
dist:  focal
addons:
  postgresql: 12
  apt:
    packages:
    - postgresql-12
    - postgresql-client-12
